trigger: none

pr: none

variables:
  - name: azureServiceConnection
    value: sc-expenseflow-azure

pool:
  name: Default
  demands:
    - Agent.Name -equals devops-self-hosted-agent

stages:
  - stage: PlanProd
    displayName: Plan prod infrastructure
    variables:
      - group: expenseflow-prod
    jobs:
      - job: PlanProd
        steps:
          - checkout: self
            fetchDepth: 0

          - task: AzureCLI@2
            displayName: Terraform prod plan
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(Build.SourcesDirectory)/expense-infra/envs/prod
              inlineScript: |
                set -euo pipefail

                terraform version

                cat > pipeline.auto.tfvars <<EOF
                subscription_id = "$(subscription_id)"
                tenant_id = "$(tenant_id)"
                key_vault_admin_object_ids = ["$(key_vault_admin_object_id)"]
                postgres_admin_password = "$(postgres_admin_password)"
                EOF

                terraform init -backend-config=backend.hcl -upgrade
                terraform validate
                terraform plan -out=tfplan

          - publish: $(Build.SourcesDirectory)/expense-infra/envs/prod/tfplan
            artifact: prod-tfplan
            displayName: Publish prod tfplan

  - stage: ApplyProd
    displayName: Apply prod infrastructure
    dependsOn: PlanProd
    variables:
      - group: expenseflow-prod
    jobs:
      - deployment: ApplyProd
        displayName: Apply prod
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  fetchDepth: 0

                - download: current
                  artifact: prod-tfplan

                - task: AzureCLI@2
                  displayName: Terraform prod apply
                  inputs:
                    azureSubscription: $(azureServiceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    workingDirectory: $(Build.SourcesDirectory)/expense-infra/envs/prod
                    inlineScript: |
                      set -euo pipefail

                      terraform version

                      cat > pipeline.auto.tfvars <<EOF
                      subscription_id = "$(subscription_id)"
                      tenant_id = "$(tenant_id)"
                      key_vault_admin_object_ids = ["$(key_vault_admin_object_id)"]
                      postgres_admin_password = "$(postgres_admin_password)"
                      EOF

                      cp "$(Pipeline.Workspace)/prod-tfplan/tfplan" ./tfplan
                      terraform init -backend-config=backend.hcl -upgrade
                      terraform apply -auto-approve tfplan
