subscription_id      = "$(subscription_id)"
location             = "Central India"
resource_group_name  = "expenseflow-tfstate-rg"
storage_account_name = "expenseflowtfstate01"
container_name       = "tfstate"
