apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "expenseflow.fullname" . }}-backend-config
  labels:
    {{- include "expenseflow.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.backend.env.APP_NAME | quote }}
  DEBUG: {{ .Values.backend.env.DEBUG | quote }}
  JWT_EXPIRE_MINUTES: {{ .Values.backend.env.JWT_EXPIRE_MINUTES | quote }}
  FRONTEND_ORIGINS: {{ .Values.backend.env.FRONTEND_ORIGINS | quote }}
  SEED_DEMO_DATA: {{ .Values.backend.env.SEED_DEMO_DATA | quote }}
  AZURE_BLOB_CONTAINER: {{ .Values.backend.env.AZURE_BLOB_CONTAINER | quote }}
  LOCAL_UPLOADS_DIR: {{ .Values.backend.env.LOCAL_UPLOADS_DIR | quote }}
