apiVersion: v1
kind: Secret
metadata:
  name: {{ include "expenseflow.fullname" . }}-backend-secret
  labels:
    {{- include "expenseflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.backend.secretEnv.JWT_SECRET | quote }}
  DATABASE_URL: {{ .Values.backend.secretEnv.DATABASE_URL | quote }}
  REDIS_URL: {{ .Values.backend.secretEnv.REDIS_URL | quote }}
  AZURE_BLOB_CONNECTION_STRING: {{ .Values.backend.secretEnv.AZURE_BLOB_CONNECTION_STRING | quote }}
